const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),$=s=>document.querySelector(s);
const bg=new Image();bg.src='festival-village.png';const W=1200,H=600,ground=510,world=4600;
let mode='intro',keys={},player,items,hazards,particles=[],camera=0,score=0,flowers=0,hearts=3,shield=0,invincible=0,time=0,last=0,checkpoint=90,puzzleDone=false,puzzleStep=0,sound=false,audioCtx;
const platforms=[{x:360,y:414,w:170},{x:720,y:358,w:170},{x:1140,y:416,w:160},{x:1530,y:356,w:170},{x:2060,y:415,w:180},{x:2430,y:352,w:180},{x:2820,y:410,w:180},{x:3200,y:350,w:180},{x:3660,y:414,w:200}];
const modakPositions=[[230,465],[410,375],[490,375],[740,318],[840,318],[1020,465],[1190,377],[1580,317],[1660,317],[1890,465],[2110,376],[2500,313],[2900,371],[3280,311],[3750,375],[3980,465],[4180,465],[4320,465]];
function reset(){player={x:90,y:ground-48,w:42,h:48,vx:0,vy:0,jumps:0,facing:1};score=0;flowers=0;hearts=3;shield=0;invincible=0;time=0;camera=0;checkpoint=90;puzzleDone=false;puzzleStep=0;particles=[];items=modakPositions.map(([x,y])=>({x,y,type:'modak',got:false}));[[800,270],[1590,267],[2180,365],[2910,320],[3790,324]].forEach(([x,y])=>items.push({x,y,type:'flower',got:false}));items.push({x:1330,y:445,type:'shield',got:false},{x:3080,y:440,type:'shield',got:false});hazards=[{x:610,w:62,type:'puddle'},{x:980,w:44,type:'coconut'},{x:1410,w:70,type:'puddle'},{x:2320,w:44,type:'coconut'},{x:2720,w:75,type:'puddle'},{x:3460,w:48,type:'coconut'}];updateHud()}
function updateHud(){$('#score').textContent=score+' / 15';$('#flowers').textContent=flowers+' / 5';$('#hearts').textContent='♥ '.repeat(hearts)+'♡ '.repeat(3-hearts);$('#hearts').setAttribute('aria-label',hearts+' hearts');const n=Math.round((Math.min(score,15)+flowers)/20*100);$('#percent').textContent=n+'%';$('#progress').style.width=n+'%';$('#chapter').textContent=player.x<1700?'01 · Marigold Lane':player.x<3300?'02 · Lantern Courtyard':'03 · The Celebration';}
function tone(freq=660,duration=.1){if(!sound)return;try{audioCtx??=new (window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.value=freq;g.gain.setValueAtTime(.06,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+duration);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+duration)}catch{}}
let toastTimer;function toast(text){$('#toast').textContent=text;$('#toast').style.opacity=1;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').style.opacity=0,2600)}
function burst(x,y,color,n=12){for(let i=0;i<n;i++)particles.push({x,y,vx:(Math.random()-.5)*180,vy:-Math.random()*220,life:1.2,color})}
function begin(){reset();mode='play';$('#overlay').style.display='none';canvas.focus();toast('Let’s go! Double jump to reach high offerings.');tone(520)}
function jump(){if(mode==='play'&&player.jumps<2){player.vy=player.jumps===0?-620:-540;player.jumps++;tone(player.jumps===1?440:620,.08)}}
function pause(){if(mode==='play'){mode='pause';keys={};show('<span class="pill">TAKE A BREATHER</span><h1>Quest paused</h1><p>Mooshak will be right here.</p><button class="primary" id="resume">Continue →</button>');$('#resume').onclick=resume}else if(mode==='pause')resume()}
function resume(){mode='play';$('#overlay').style.display='none';canvas.focus()}
function show(html){$('#overlay').innerHTML='<div class="intro">'+html+'</div>';$('#overlay').style.display='flex'}
function puzzle(){mode='puzzle';keys={};puzzleStep=0;show('<span class="pill">THE LAMP GATE</span><h1>Light the way</h1><p>Light the lamps in this order:<br><b>🌸 Pink → 🌼 Yellow → 🪷 Lotus</b></p><div class="puzzle-buttons"><button data-lamp="1" aria-label="Yellow flower lamp">🌼</button><button data-lamp="2" aria-label="Lotus lamp">🪷</button><button data-lamp="0" aria-label="Pink flower lamp">🌸</button></div><p id="puzzle-note">Choose the first lamp.</p>');document.querySelectorAll('[data-lamp]').forEach(b=>b.onclick=()=>{if(Number(b.dataset.lamp)===puzzleStep){b.disabled=true;b.style.opacity=.45;puzzleStep++;tone(450+puzzleStep*180);$('#puzzle-note').textContent=puzzleStep+' of 3 lamps lit';if(puzzleStep===3){puzzleDone=true;checkpoint=1910;resume();toast('The path is open! Bappa’s blessing: 8 seconds.');shield=8}}else{$('#puzzle-note').textContent='Try again: pink, yellow, then lotus.';puzzleStep=0;document.querySelectorAll('[data-lamp]').forEach(b=>{b.disabled=false;b.style.opacity=1})}})}
function finish(){mode='win';tone(880,.5);show('<span class="pill">GANPATI BAPPA MORYA!</span><div class="mouse">🌺 🪔 🌺</div><h1>A celebration<br><em>you brought to life.</em></h1><p>The offerings are ready and the pandal is glowing.<br>Thank you, little Mooshak!</p><p class="result-stats">'+score+' modaks · '+flowers+' flowers · '+Math.floor(time/60)+':'+String(Math.floor(time%60)).padStart(2,'0')+'</p><button class="primary" id="again">Play again ↻</button>');$('#again').onclick=begin;for(let i=0;i<90;i++)burst(camera+Math.random()*W,Math.random()*H,['#ffcf6d','#fa8874','#f2a8be'][i%3],1)}
function hit(){if(invincible>0||shield>0)return;hearts--;invincible=2;player.vy=-280;tone(140,.2);updateHud();if(hearts<=0){mode='over';show('<span class="pill">EVERY ADVENTURE TAKES PRACTICE</span><h1>One more try?</h1><p>You collected '+score+' modaks and '+flowers+' flowers.<br>The celebration is waiting for you.</p><button class="primary" id="retry">Try again ↻</button>');$('#retry').onclick=begin}else toast('Oops! '+hearts+' hearts left. Jump over obstacles.')}
function update(dt){if(mode!=='play')return;time+=dt;shield=Math.max(0,shield-dt);invincible=Math.max(0,invincible-dt);$('#blessing').textContent=shield>0?'✦ Bappa’s Blessing · '+Math.ceil(shield)+'s':'';const direction=(keys.ArrowRight||keys.KeyD?1:0)-(keys.ArrowLeft||keys.KeyA?1:0);player.vx=direction*310;if(direction)player.facing=direction;const oldY=player.y;player.vy+=1650*dt;player.x=Math.max(20,Math.min(world-80,player.x+player.vx*dt));player.y+=player.vy*dt;if(player.y+player.h>=ground){player.y=ground-player.h;player.vy=0;player.jumps=0}for(const p of platforms){if(player.vy>=0&&oldY+player.h<=p.y+2&&player.y+player.h>=p.y&&player.x+player.w>p.x&&player.x<p.x+p.w){player.y=p.y-player.h;player.vy=0;player.jumps=0}}
for(const it of items)if(!it.got&&Math.hypot(player.x+21-it.x,player.y+24-it.y)<44){it.got=true;if(it.type==='modak'){score++;tone(740)}else if(it.type==='flower'){flowers++;tone(980);toast('A flower for the pandal! '+flowers+' / 5')}else{shield=8;tone(1100,.25);toast('Bappa’s Blessing! You’re protected for 8 seconds.')}burst(it.x,it.y,it.type==='flower'?'#ff9bac':'#ffcf6d');updateHud()}
for(const h of hazards)if(player.x+player.w>h.x+8&&player.x<h.x+h.w-8&&player.y+player.h>ground-(h.type==='puddle'?8:34))hit();if(player.x>1790&&!puzzleDone)puzzle();if(player.x>4410){if(score>=15&&flowers>=5)finish();else{player.x=4390;toast('Bring 15 modaks and 5 flowers. Explore back along the trail!')}}camera=Math.max(0,Math.min(world-W,player.x-330));updateHud();}
function emoji(text,x,y,size=32){ctx.font=size+'px "Apple Color Emoji","Segoe UI Emoji",sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,x,y)}
function draw(dt){ctx.clearRect(0,0,W,H);if(bg.complete&&bg.naturalWidth){ctx.drawImage(bg,0,0,W,H);ctx.fillStyle='#073c422a';ctx.fillRect(0,0,W,H)}else{ctx.fillStyle='#19534e';ctx.fillRect(0,0,W,H)}ctx.fillStyle='#072c3290';ctx.fillRect(0,ground,W,H-ground);ctx.fillStyle='#b9b878';ctx.fillRect(0,ground,W,3);ctx.save();ctx.translate(-camera,0);for(const p of platforms){ctx.fillStyle='#163c3b';ctx.beginPath();ctx.roundRect(p.x,p.y,p.w,20,6);ctx.fill();ctx.fillStyle='#ffc76b';ctx.fillRect(p.x+5,p.y,p.w-10,4);ctx.fillStyle='#d79b48';for(let x=p.x+12;x<p.x+p.w;x+=24){ctx.beginPath();ctx.arc(x,p.y+12,3,0,7);ctx.fill()}}for(const h of hazards){if(h.type==='puddle'){ctx.fillStyle='#6ab5be';ctx.beginPath();ctx.ellipse(h.x+h.w/2,ground,h.w/2,7,0,0,7);ctx.fill();ctx.strokeStyle='#c6e8e3';ctx.stroke()}else emoji('🥥',h.x+h.w/2,ground-19,39)}for(const it of items)if(!it.got){const yy=it.y+Math.sin(time*3+it.x)*4;ctx.fillStyle=it.type==='flower'?'#ffa9ad20':'#ffcf6d20';ctx.beginPath();ctx.arc(it.x,yy,23,0,7);ctx.fill();emoji(it.type==='modak'?'🥟':it.type==='flower'?'🌼':'✨',it.x,yy,it.type==='shield'?38:30)}
if(!puzzleDone){ctx.strokeStyle='#ffcf6d';ctx.lineWidth=4;ctx.setLineDash([6,9]);ctx.beginPath();ctx.moveTo(1840,ground);ctx.lineTo(1840,ground-155);ctx.stroke();ctx.setLineDash([]);emoji('🪔',1840,ground-175,40)}
ctx.fillStyle='#123b36dd';ctx.beginPath();ctx.roundRect(4390,ground-190,190,165,15);ctx.fill();ctx.strokeStyle='#ffcf6d';ctx.lineWidth=2;ctx.stroke();emoji('🪔',4485,ground-145,43);ctx.fillStyle='#ffe2a0';ctx.font='bold 18px sans-serif';ctx.textAlign='center';ctx.fillText('THE PANDAL',4485,ground-105);for(let i=0;i<flowers;i++)emoji('🌼',4420+i*32,ground-65,26);if(score>=15)emoji('🥟 🥟 🥟',4485,ground-30,24);
ctx.save();ctx.translate(player.x+21,player.y+25);if(shield>0){ctx.strokeStyle='#ffe8a3';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,37+Math.sin(time*6)*2,0,7);ctx.stroke()}if(invincible<=0||Math.floor(invincible*12)%2===0){ctx.scale(-player.facing,1);emoji('🐁',0,0,53)}ctx.restore();for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=300*dt;p.life-=dt;ctx.globalAlpha=Math.max(0,p.life);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,5,7)}ctx.globalAlpha=1;particles=particles.filter(p=>p.life>0);ctx.restore()}
function frame(t){const dt=Math.min((t-last)/1000||0,.034);last=t;update(dt);draw(dt);requestAnimationFrame(frame)}
$('#start').onclick=begin;$('#pause').onclick=pause;$('#sound').onclick=()=>{sound=!sound;$('#sound').textContent=sound?'Sound on':'Sound off';$('#sound').setAttribute('aria-label',sound?'Disable sound':'Enable sound');tone(650)};
window.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','Space','KeyA','KeyD','KeyW','KeyP','Escape'].includes(e.code)){e.preventDefault();if(!e.repeat&&['Space','ArrowUp','KeyW'].includes(e.code))jump();if(!e.repeat&&['KeyP','Escape'].includes(e.code))pause();keys[e.code]=true}});window.addEventListener('keyup',e=>keys[e.code]=false);window.addEventListener('blur',()=>{keys={};if(mode==='play')pause()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&mode==='play')pause()});document.querySelectorAll('[data-key]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys[b.dataset.key]=true;if(b.dataset.key==='Space')jump()});for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>keys[b.dataset.key]=false)});reset();requestAnimationFrame(frame);
