'use strict';
const $=s=>document.querySelector(s),canvas=$('#game'),ctx=canvas.getContext('2d');
const W=1200,H=600,G=510,LENGTH=3000,REQUIRED=8,TOTAL=10,FLOWERS=3;
const bg=new Image();bg.src='festival-village.png';
const levels=[
 {name:'Marigold Streets',desc:'Hop over puddles. Remember the lamps.',color:'#18584e',tint:'#07534122',puzzle:'memory',hazards:[{x:550,type:'puddle'},{x:1040,type:'coconut'},{x:1720,type:'puddle'},{x:2430,type:'coconut'}],gaps:[[2060,2140]]},
 {name:'Temple Garden',desc:'Cross the garden. Complete the rangoli.',color:'#286044',tint:'#4e852640',puzzle:'rangoli',hazards:[{x:540,type:'coconut'},{x:1070,type:'cart'},{x:1710,type:'puddle'},{x:2410,type:'coconut'}],gaps:[[2020,2150]]},
 {name:'Grand Pandal',desc:'Follow the rhythm. Bring the festival home.',color:'#34316b',tint:'#34217d55',puzzle:'rhythm',hazards:[{x:550,type:'cart'},{x:1070,type:'coconut'},{x:1720,type:'cart'},{x:2430,type:'coconut'}],gaps:[[2050,2170]]}
];
const platformLayout=[{x:340,y:408,w:180},{x:730,y:340,w:170},{x:1130,y:404,w:180},{x:1610,y:370,w:160},{x:1930,y:407,w:150},{x:2230,y:350,w:180},{x:2580,y:409,w:160}];
let mode='intro',level=0,player,items,hazards,keys={},camera=0,hearts=3,damage=0,elapsed=0,totalTime=0,magnet=0,shield=0,invincible=0,checkpoint=80,checkActive=false,puzzleDone=false,particles=[],results=[],decor=[],last=0,clock=0,puzzleToken=0,currentHint='',hintUntil=0;
let sound=false,audioCtx,musicTimer,musicBeat=0;
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const rewardKey='mooshak-adventure-rewards-v1';
let rewards={unlocked:false,outfit:'classic'},rewardsSaved=true;
try{const saved=JSON.parse(localStorage.getItem(rewardKey)||'null');if(saved?.unlocked===true){rewards.unlocked=true;if(['classic','crown','lotus'].includes(saved.outfit))rewards.outfit=saved.outfit}}catch{}
function saveRewards(){try{localStorage.setItem(rewardKey,JSON.stringify(rewards));rewardsSaved=true}catch{rewardsSaved=false}}
function journey(){return '<ol class="journey">'+levels.map((l,i)=>'<li class="'+(results[i]?'done':i===level?'current':'locked')+'" '+(i===level?'aria-current="step"':'')+'><b>'+ (results[i]?'✓':i>level?'🔒':i+1)+'</b><span>Level '+(i+1)+'<small>'+['Streets','Garden','Pandal'][i]+'</small></span></li>').join('')+'</ol>'}
function prepareLevel(n){if(n>results.length)return;loadLevel(n);mode='briefing';show('<span class="pill">'+(n===0?'YOUR ADVENTURE STARTS HERE':'LEVEL '+n+' COMPLETE · LEVEL '+(n+1)+' UNLOCKED')+'</span>'+journey()+'<h1>Level '+(n+1)+'<br><em>'+levels[n].name+'</em></h1><p>'+['Jump over puddles and repeat the glowing lamps.','Cross the garden and make an X-shaped rangoli.','Dodge moving carts and catch four drum beats.'][n]+'</p><p class="mission-goal">🥟 Collect 8 modaks &nbsp; 🌼 Find all 3 flowers<br>🪔 Solve the puzzle, then reach the exit.</p><button class="primary" id="begin-level">▶ Play Level '+(n+1)+'</button><p class="small">'+(n<2?'Complete this level to unlock Level '+(n+2)+'.':'Complete Level 3 to unlock your trophy and bonus outfits!')+'</p>');$('#begin-level').onclick=()=>{mode='play';hide();toast(levels[n].desc)}}
function goodies(){if(!rewards.unlocked)return;mode='goodies';show('<span class="pill">ALL THREE LEVELS COMPLETE</span><h1>Your festival goodies!</h1><div class="reward-trophy">🏆</div><p><b>Festival Hero trophy earned!</b><br>Golden crown and lotus scarf unlocked.</p><canvas id="outfit-preview" width="180" height="80" aria-label="Mooshak outfit preview"></canvas><div class="choices">'+[['classic','Classic Mooshak'],['crown','👑 Golden crown'],['lotus','🪷 Lotus scarf']].map(([id,name])=>'<button data-outfit="'+id+'" aria-pressed="'+(rewards.outfit===id)+'">'+name+'</button>').join('')+'</div><p id="reward-note" class="small">'+(rewardsSaved?'Your goodies are saved in this browser.':'Goodies are available for this visit; browser storage is unavailable.')+'</p><div class="actions"><button class="primary" id="replay-outfit">▶ Play with this outfit</button><button id="goodies-back">'+(results.length===3?'Back to celebration':'Back to title')+'</button></div>');document.querySelectorAll('[data-outfit]').forEach(b=>b.onclick=()=>{rewards.outfit=b.dataset.outfit;saveRewards();document.querySelectorAll('[data-outfit]').forEach(bb=>bb.setAttribute('aria-pressed',String(bb.dataset.outfit===rewards.outfit)));$('#reward-note').textContent=rewardsSaved?'Outfit saved! Wear it on your next adventure.':'Outfit selected for this visit.';tone(880)});$('#replay-outfit').onclick=start;$('#goodies-back').onclick=()=>results.length===3?win():intro()}
function tone(freq=660,duration=.12,type='sine',volume=.04,delay=0){if(!sound)return;try{audioCtx??=new (window.AudioContext||window.webkitAudioContext)();const at=audioCtx.currentTime+delay,o=audioCtx.createOscillator(),gain=audioCtx.createGain();o.type=type;o.frequency.setValueAtTime(freq,at);gain.gain.setValueAtTime(volume,at);gain.gain.exponentialRampToValueAtTime(.001,at+duration);o.connect(gain);gain.connect(audioCtx.destination);o.start(at);o.stop(at+duration)}catch{}}
function music(){if(!sound||document.hidden||!['play','decorate','win'].includes(mode))return;const melody=[523,659,784,659,587,698,880,784,659,587,523,392,440,523,587,659];tone(melody[musicBeat%melody.length],.22,'triangle',.018);tone(musicBeat%4===0?90:145,.1,'sine',.055);musicBeat++}
function fanfare(){[523,659,784,1047].forEach((n,i)=>tone(n,.3,'triangle',.05,i*.14))}
$('#sound').onclick=async()=>{sound=!sound;$('#sound').textContent=sound?'♪ Sound on':'♪ Sound off';$('#sound').setAttribute('aria-pressed',String(sound));if(sound){tone();try{await audioCtx?.resume()}catch{}musicTimer=setInterval(music,260)}else{clearInterval(musicTimer);try{await audioCtx?.suspend()}catch{}}};
function toast(text){$('#toast').textContent=text;$('#toast').style.opacity=1;hintUntil=clock+3.2}
function hide(){puzzleToken++;$('#overlay').hidden=true;keys={};canvas.focus()}
function show(html){puzzleToken++;keys={};$('#overlay').hidden=false;$('#overlay').innerHTML='<div class="panel">'+html+'</div>';$('#overlay').querySelector('button')?.focus()}
function format(t){return Math.floor(t/60)+':'+String(Math.floor(t%60)).padStart(2,'0')}
function counts(){return {modaks:items.filter(i=>i.type==='modak'&&i.got).length,flowers:items.filter(i=>i.type==='flower'&&i.got).length}}
function hud(){const c=counts();$('#score').textContent=c.modaks+' / '+REQUIRED;$('#flowers').textContent=c.flowers+' / '+FLOWERS;$('#hearts').textContent='♥ '.repeat(hearts)+'♡ '.repeat(3-hearts);$('#hearts').setAttribute('aria-label',hearts+' hearts');$('#chapter').textContent=levels[level].name;$('#level-label').textContent='LEVEL '+(level+1)+' OF 3';$('#level-trail').innerHTML=journey();$('#timer').textContent=format(totalTime+elapsed);$('#checkpoint').textContent=checkActive?'⚑ Checkpoint saved':'⚑ Checkpoint ahead';$('#objective').textContent=puzzleDone?'Bring 8 modaks + 3 flowers to the exit →':'Collect 8 modaks + 3 flowers · Solve the gate puzzle';$('#powers').textContent=[magnet>0?'🧲 Magnet '+Math.ceil(magnet)+'s':'',shield>0?'✦ Blessing '+Math.ceil(shield)+'s':''].filter(Boolean).join(' · ')}
function loadLevel(n){level=n;player={x:80,y:G-44,w:40,h:44,vx:0,vy:0,jumps:0,facing:1};camera=0;hearts=3;damage=0;elapsed=0;checkpoint=80;checkActive=false;puzzleDone=false;magnet=0;shield=0;invincible=0;particles=[];currentHint='';items=[[220,466],[410,368],[780,300],[870,300],[1200,364],[1660,330],[1990,367],[2300,310],[2640,369],[2810,466]].map(([x,y])=>({x,y,type:'modak',got:false}));[[805,256],[1670,282],[2330,263]].forEach(([x,y])=>items.push({x,y,type:'flower',got:false}));items.push({x:650,y:465,type:'magnet',got:false},{x:1810,y:463,type:'shield',got:false});hazards=levels[n].hazards.map(h=>({...h,baseX:h.x,w:h.type==='cart'?66:48}));mode='play';hide();hud();toast(levels[n].desc)}
function start(){results=[];decor=[];totalTime=0;prepareLevel(0)}
function intro(){mode='intro';show('<span class="pill">THE GRAND ADVENTURE</span><h1>Mooshak’s<br><em>Modak Mission</em></h1><p>Play Level 1, then unlock Level 2, then Level 3.</p>'+journey()+'<p>Finish all three to earn a trophy and bonus outfits!</p><div class="actions"><button id="start" class="primary">▶ Play</button>'+(rewards.unlocked?'<button id="my-goodies">🏆 My goodies</button>':'')+'</div><p class="small">Move: ← → / A D · Double jump: Space<br>Use: E · Mobile: buttons below the game</p>');$('#start').onclick=start;if($('#my-goodies'))$('#my-goodies').onclick=goodies}
function jump(){if(mode==='play'&&player.jumps<2){player.vy=player.jumps===0?-630:-550;player.jumps++;tone(player.jumps===1?440:600,.09,'triangle')}}
function pause(){if(mode==='play'){mode='pause';show('<span class="pill">TAKE A BREATHER</span><h1>Quest paused</h1><p>Your checkpoint and offerings are safe.</p><div class="actions"><button class="primary" id="resume">Continue →</button><button id="restart">Restart level</button></div>');$('#resume').onclick=()=>{mode='play';hide()};$('#restart').onclick=()=>loadLevel(level)}else if(mode==='pause'){mode='play';hide()}}
function burst(x,y,color,n=14){if(reduced)n=4;for(let i=0;i<n;i++)particles.push({x,y,vx:(Math.random()-.5)*180,vy:-Math.random()*180,life:1,color})}
function respawn(){player.x=checkpoint;player.y=G-player.h;player.vx=player.vy=0;player.jumps=0;camera=Math.max(0,Math.min(LENGTH-W,player.x-330));invincible=2;keys={}}
function hit(fall=false){if(!fall&&(invincible>0||shield>0))return;if(fall&&shield>0){respawn();toast('Blessing brought you back to the checkpoint.');return}hearts--;damage++;tone(130,.18,'sawtooth',.035);if(hearts<=0){mode='over';show('<span class="pill">EVERY ADVENTURE TAKES PRACTICE</span><h1>One more try?</h1><p>Restart '+levels[level].name+'.<br>Your earlier level results and decorations are safe.</p><button class="primary" id="retry">Retry this level ↻</button>');$('#retry').onclick=()=>loadLevel(level)}else{respawn();toast(checkActive?'Back at your checkpoint. Offerings kept!':'Back at the start. Offerings kept!')}hud()}
function nearPuzzle(){return Math.abs(player.x-1450)<125}
function interact(){if(mode!=='play')return;if(nearPuzzle()&&!puzzleDone){openPuzzle();return}if(player.x>2750){exitLevel();return}toast('Use near a lamp gate or the level exit.')}
function openPuzzle(){mode='puzzle';const type=levels[level].puzzle;if(type==='memory')memoryPuzzle();else if(type==='rangoli')rangoliPuzzle();else rhythmPuzzle()}
function puzzleShell(title,description,body){show('<span class="pill">'+levels[level].name.toUpperCase()+' · FESTIVAL PUZZLE</span><h1>'+title+'</h1><p>'+description+'</p>'+body+'<p id="puzzle-note" role="status" aria-live="polite"></p><button id="back" class="small">Back to the trail</button>');$('#back').onclick=()=>{mode='play';hide()}}
function solved(){puzzleDone=true;mode='play';hide();shield=8;burst(1490,380,'#ffcf6d',30);fanfare();toast('Gate opened! Enjoy 8 seconds of Bappa’s blessing.');hud()}
function memoryPuzzle(){const sequence=[0,2,1,0];let position=0,busy=true;puzzleShell('Remember the glow','Watch four lamps, then repeat their order.',['<div class="puzzle-buttons">',...['🌸','🌼','🪷'].map((s,i)=>'<button data-lamp="'+i+'">'+s+'<small>'+['Pink','Yellow','Lotus'][i]+'</small></button>'),'</div><button id="watch">Watch again</button>'].join(''));const token=puzzleToken,buttons=[...document.querySelectorAll('[data-lamp]')];function watch(){if(busy&&position===-1)return;position=-1;busy=true;buttons.forEach(b=>b.disabled=true);$('#watch').disabled=true;$('#puzzle-note').textContent='Watch closely…';let t=0;sequence.forEach((n,i)=>{setTimeout(()=>{if(token!==puzzleToken)return;buttons[n].classList.add('lit');$('#puzzle-note').textContent=(i+1)+' / 4 · '+['Pink','Yellow','Lotus'][n];tone(500+n*160)},t+300);setTimeout(()=>{if(token===puzzleToken)buttons[n].classList.remove('lit')},t+850);t+=850});setTimeout(()=>{if(token!==puzzleToken)return;busy=false;position=0;buttons.forEach(b=>b.disabled=false);$('#watch').disabled=false;$('#puzzle-note').textContent='Your turn: repeat the four lamps.'},t+200)}buttons.forEach((b,i)=>b.onclick=()=>{if(busy)return;if(i===sequence[position]){position++;tone(600+position*90);$('#puzzle-note').textContent=position+' / 4 correct';if(position===sequence.length)solved()}else{position=0;$('#puzzle-note').textContent='Try again, or watch the sequence once more.';tone(180)}});$('#watch').onclick=watch;watch()}
function rangoliPuzzle(){let cells=Array(9).fill(0);const pattern=[1,0,1,0,1,0,1,0,1];puzzleShell('Finish the rangoli','Make an X: light the four corners and the center. Tap a tile to change it.','<div class="rangoli">'+cells.map((_,i)=>'<button data-cell="'+i+'" aria-label="Tile '+(i+1)+'" aria-pressed="false">○</button>').join('')+'</div><button class="primary" id="check-pattern">Check pattern</button>');document.querySelectorAll('[data-cell]').forEach((b,i)=>b.onclick=()=>{cells[i]=1-cells[i];b.textContent=cells[i]?'🌼':'○';b.classList.toggle('lit',!!cells[i]);b.setAttribute('aria-pressed',String(!!cells[i]));tone(cells[i]?700:400)});$('#check-pattern').onclick=()=>{if(cells.every((v,i)=>v===pattern[i]))solved();else $('#puzzle-note').textContent='Almost! Only the four corners and center should glow.'}}
function rhythmPuzzle(){let hits=0,ready=false,beatIndex=0;puzzleShell('Follow the festival beat','Tap the drum while it glows. Catch four beats; a miss resets your streak.','<div class="puzzle-buttons"><button id="drum" aria-label="Drum, wait for glow">🥁<small>Wait…</small></button></div><button id="easy">Use a slower beat</button>');const token=puzzleToken;let period=1400,windowMs=850;function beat(){if(token!==puzzleToken)return;ready=true;beatIndex++;const thisBeat=beatIndex;$('#drum').classList.add('lit');$('#drum').innerHTML='🥁<small>Tap now!</small>';$('#drum').setAttribute('aria-label','Drum, tap now');tone(110,.15,'sine',.08);setTimeout(()=>{if(token!==puzzleToken||thisBeat!==beatIndex)return;if(ready){hits=0;$('#puzzle-note').textContent='Missed it! Catch the next glow.'}ready=false;$('#drum').classList.remove('lit');$('#drum').innerHTML='🥁<small>Wait…</small>';$('#drum').setAttribute('aria-label','Drum, wait for glow')},windowMs);setTimeout(beat,period)}$('#drum').onclick=()=>{if(ready){ready=false;hits++;$('#puzzle-note').textContent=hits+' / 4 beats caught';tone(220,.12);$('#drum').classList.remove('lit');if(hits===4)solved()}else{hits=0;$('#puzzle-note').textContent='Wait for the glow, then tap once.'}};$('#easy').onclick=()=>{period=2200;windowMs=1600;$('#easy').textContent='Slower beat enabled';$('#easy').disabled=true};beat()}
function exitLevel(){if(mode!=='play')return;const c=counts();if(!puzzleDone||c.modaks<REQUIRED||c.flowers<FLOWERS){toast(!puzzleDone?'Solve this level’s gate puzzle first.':'Need 8 modaks and all 3 flowers. Explore back along the trail.');return}const stars=1+(c.modaks===TOTAL&&c.flowers===FLOWERS?1:0)+(damage===0?1:0);const result={name:levels[level].name,stars,modaks:c.modaks,flowers:c.flowers,time:elapsed,perfect:damage===0};results[level]=result;totalTime+=elapsed;mode='result';fanfare();show('<span class="pill">LEVEL '+(level+1)+' COMPLETE</span><h1>'+result.name+'</h1><div class="stars">'+'★'.repeat(stars)+'☆'.repeat(3-stars)+'</div><p>'+c.modaks+' / 10 modaks · 3 / 3 flowers · '+format(elapsed)+'</p><div class="star-rules">★ Complete the level<br>'+(c.modaks===10?'★':'☆')+' Find all 10 modaks and 3 flowers<br>'+(damage===0?'★':'☆')+' Finish without losing a heart</div><p class="small">'+(level<2?'Next: place your decoration to unlock Level '+(level+2)+'.':'Place the final decoration to claim your goodies!')+'</p><button class="primary" id="decorate">Decorate & continue →</button>');$('#decorate').onclick=decorate}
const decorations=[['🌼 Marigold garland','🌺 Hibiscus garland','🪷 Lotus garland'],['🪔 Clay lamps','🏮 Paper lanterns','✨ Star lights'],['🌸 Pink rangoli','🌼 Golden rangoli','🪷 Lotus rangoli']];
function previewDecor(choice){const choices=[...decor];choices[level]=choice;const garland=['🌼','🌺','🪷'][choices[0]??0],lamp=['🪔','🏮','✨'][choices[1]??0],rangoli=['🌸','🌼','🪷'][choices[2]??0];return '<div>'+garland.repeat(7)+'</div><div>'+lamp+' &nbsp; 🕉️ &nbsp; '+lamp+'</div><div class="offerings">🥟 🥟 🥟</div><div>'+rangoli+' '+rangoli+' '+rangoli+'</div>'}
function decorate(){mode='decorate';let selected=0;show('<span class="pill">YOUR OFFERINGS BECOME A CELEBRATION</span><h1>'+['Choose your garland','Light your pandal','Add the final rangoli'][level]+'</h1><p>Use this level’s 3 flowers and 8 modaks to unlock a decoration.</p><div class="pandal-preview" id="pandal-preview">'+previewDecor(selected)+'</div><div class="choices">'+decorations[level].map((s,i)=>'<button data-decor="'+i+'" aria-pressed="'+(i===0)+'">'+s+'</button>').join('')+'</div><button class="primary" id="place">'+(level<2?'Place & unlock Level '+(level+2)+' →':'Finish & claim goodies →')+'</button>');document.querySelectorAll('[data-decor]').forEach((b,i)=>b.onclick=()=>{selected=i;document.querySelectorAll('[data-decor]').forEach((bb,j)=>bb.setAttribute('aria-pressed',String(i===j)));$('#pandal-preview').innerHTML=previewDecor(selected);tone(660+i*110)});$('#place').onclick=()=>{decor[level]=selected;if(level<2)prepareLevel(level+1);else win()}}
function win(){if(results.length!==3)return;mode='win';rewards.unlocked=true;saveRewards();fanfare();show('<span class="pill">GANPATI BAPPA MORYA!</span><canvas id="victory-mouse" width="180" height="65" aria-label="Mooshak dances in celebration"></canvas><h1>A little mouse.<br><em>A grand celebration.</em></h1><div class="pandal-preview">'+previewDecor(decor[2])+'</div><div class="results">'+results.map((r,i)=>'<div>'+['Streets','Garden','Pandal'][i]+'<b>'+'★'.repeat(r.stars)+'☆'.repeat(3-r.stars)+'</b></div>').join('')+'</div><p>'+results.reduce((s,r)=>s+r.modaks,0)+' / 30 modaks · 9 flowers · '+format(totalTime)+'<br>Your chosen decorations light up the pandal.</p><div class="actions"><button class="primary" id="open-goodies">🎁 Open your goodies</button><button id="again">Play again ↻</button></div>');$('#again').onclick=start;$('#open-goodies').onclick=goodies;for(let i=0;i<80;i++)burst(camera+Math.random()*W,Math.random()*H,'#ffcf6d',1)}
function update(dt){if(mode!=='play')return;elapsed+=dt;magnet=Math.max(0,magnet-dt);shield=Math.max(0,shield-dt);invincible=Math.max(0,invincible-dt);const dir=(keys.ArrowRight||keys.KeyD?1:0)-(keys.ArrowLeft||keys.KeyA?1:0);player.vx=dir*300;if(dir)player.facing=dir;const oldBottom=player.y+player.h;player.vy+=1650*dt;player.x=Math.max(8,Math.min(LENGTH-55,player.x+player.vx*dt));if(!puzzleDone&&player.x>1490)player.x=1490;player.y+=player.vy*dt;const overGap=levels[level].gaps.some(([a,b])=>player.x+player.w*.65>a&&player.x+player.w*.35<b);if(!overGap&&player.vy>=0&&oldBottom<=G+3&&player.y+player.h>=G){player.y=G-player.h;player.vy=0;player.jumps=0}for(const p of platformLayout){if(player.vy>=0&&oldBottom<=p.y+3&&player.y+player.h>=p.y&&player.x+player.w>p.x&&player.x<p.x+p.w){player.y=p.y-player.h;player.vy=0;player.jumps=0}}if(player.y>H+90){hit(true);return}for(const it of items){if(it.got)continue;const dx=player.x+20-it.x,dy=player.y+22-it.y,dist=Math.hypot(dx,dy);if(magnet>0&&it.type==='modak'&&dist<190&&dist>1){it.x+=dx*Math.min(1,dt*7);it.y+=dy*Math.min(1,dt*7)}if(dist<43){it.got=true;if(it.type==='magnet'){magnet=12;toast('Modak magnet! Nearby modaks fly to you for 12 seconds.');tone(1000,.2)}else if(it.type==='shield'){shield=8;toast('Bappa’s blessing! Protected for 8 seconds.')}else{tone(it.type==='flower'?980:740);burst(it.x,it.y,it.type==='flower'?'#ff9fae':'#ffcf6d')}hud()}}for(const h of hazards){h.x=h.baseX+(h.type==='cart'?Math.sin(elapsed*1.5)*58:0);if(player.x+player.w>h.x+8&&player.x<h.x+h.w-8&&player.y+player.h>G-(h.type==='puddle'?9:h.type==='cart'?43:32)){hit();if(mode!=='play')return}}if(player.x>1320&&!checkActive){checkActive=true;checkpoint=1330;toast('Checkpoint saved! Collected offerings stay with you.');tone(880,.2)}if(nearPuzzle()&&!puzzleDone&&currentHint!=='gate'){currentHint='gate';toast('Lamp gate: press E or USE to solve the puzzle.')}if(player.x>2820){exitLevel();if(mode==='play')player.x=2810}camera=Math.max(0,Math.min(LENGTH-W,player.x-330));hud()}
function emoji(text,x,y,size=30){ctx.font=size+'px "Apple Color Emoji","Segoe UI Emoji","Noto Color Emoji",sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,x,y)}
function ellipse(x,y,rx,ry,color){ctx.fillStyle=color;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fill()}
function mouse(x,y,c=ctx){const ellipse=(x,y,rx,ry,color)=>{c.fillStyle=color;c.beginPath();c.ellipse(x,y,rx,ry,0,0,Math.PI*2);c.fill()};const running=(Math.abs(player.vx)>0&&mode==='play')||mode==='win',phase=reduced?0:clock*(running?18:4),bounce=running?Math.abs(Math.sin(phase))*3:Math.sin(phase)*1.2;c.save();c.translate(x,y+bounce);if(mode==='win'&&!reduced)c.rotate(Math.sin(clock*7)*.16);c.scale(player.facing,1);if(invincible>0&&Math.floor(invincible*12)%2===0)c.globalAlpha=.35;c.strokeStyle='#f0b2ba';c.lineWidth=4;c.lineCap='round';c.beginPath();c.moveTo(-15,10);c.bezierCurveTo(-40,3+Math.sin(phase)*6,-42,28,-56,19+Math.sin(phase)*4);c.stroke();ellipse(-2,7,23,17,'#b6c8cd');ellipse(13,-1,15,14,'#d7e1df');ellipse(5,-14+Math.sin(phase)*2,10,12,'#a6bbc1');ellipse(5,-14+Math.sin(phase)*2,6,8,'#efaeb7');ellipse(20,-3,2.5,3,'#0b2830');ellipse(29,2,4,3,'#f4abb8');ellipse(-12,21,8,3,'#edc2c1');ellipse(12+Math.sin(phase)*3,21,7,3,'#edc2c1');c.strokeStyle='#829f9e';c.lineWidth=1;for(let j=-1;j<=1;j++){c.beginPath();c.moveTo(25,5);c.lineTo(40,5+j*6);c.stroke()}c.fillStyle=rewards.outfit==='lotus'?'#f0a4d0':'#f9c764';c.fillRect(-1,0,6,13);if(rewards.unlocked&&rewards.outfit==='lotus'){c.fillStyle='#ce78b0';c.beginPath();c.moveTo(2,8);c.lineTo(-17,15);c.lineTo(-9,20);c.lineTo(4,12);c.fill()}if(rewards.unlocked&&rewards.outfit==='crown'){c.fillStyle='#ffcf6d';c.beginPath();c.moveTo(3,-18);c.lineTo(0,-30);c.lineTo(9,-25);c.lineTo(14,-34);c.lineTo(19,-25);c.lineTo(28,-30);c.lineTo(25,-18);c.closePath();c.fill();ellipse(14,-22,2,2,'#d56288')}c.restore()}
function draw(dt){ctx.fillStyle=levels[level].color;ctx.fillRect(0,0,W,H);if(bg.complete&&bg.naturalWidth){ctx.drawImage(bg,0,0,W,H);ctx.fillStyle=levels[level].tint;ctx.fillRect(0,0,W,H)}ctx.fillStyle='#082e3655';ctx.fillRect(0,0,W,H);if(level===1){for(let i=0;i<8;i++)emoji('🌿',i*185-camera*.15%185,450,54)}if(level===2){for(let i=0;i<9;i++)emoji('🏮',i*155-camera*.12%155,75+Math.sin(i)*12,35)}ctx.save();ctx.translate(-camera,0);ctx.fillStyle='#113c3d';ctx.fillRect(0,G,LENGTH,90);ctx.fillStyle='#d9b778';ctx.fillRect(0,G,LENGTH,4);for(const [a,b]of levels[level].gaps){ctx.fillStyle='#06252e';ctx.fillRect(a,G,b-a,90);emoji('💧',(a+b)/2,G+44,30)}for(const p of platformLayout){ctx.fillStyle=level===1?'#385b39':'#173f40';ctx.beginPath();ctx.roundRect(p.x,p.y,p.w,20,6);ctx.fill();ctx.fillStyle='#ffcb6d';ctx.fillRect(p.x+4,p.y,p.w-8,4);for(let x=p.x+18;x<p.x+p.w;x+=32)ellipse(x,p.y+12,3,3,'#e9b45a')}for(const h of hazards){if(h.type==='puddle'){ellipse(h.x+24,G,29,7,'#7cc4d4')}else emoji(h.type==='cart'?'🛒':'🥥',h.x+h.w/2,G-22,h.type==='cart'?49:38)}for(const it of items){if(it.got)continue;const y=it.y+(reduced?0:Math.sin(clock*3+it.x)*4);ellipse(it.x,y,23,23,it.type==='flower'?'#ff9bac30':'#ffd47725');emoji({modak:'🥟',flower:'🌼',magnet:'🧲',shield:'✨'}[it.type],it.x,y,31)}ctx.fillStyle='#dcc276';ctx.fillRect(1340,G-95,3,95);emoji(checkActive?'🚩':'⚑',1361,G-84,32);ctx.font='14px sans-serif';ctx.textAlign='center';ctx.fillStyle='#fff0c9';ctx.fillText('CHECKPOINT',1340,G-115);if(!puzzleDone){ctx.strokeStyle='#ffcf6d';ctx.lineWidth=4;ctx.setLineDash([8,8]);ctx.beginPath();ctx.moveTo(1535,G);ctx.lineTo(1535,G-175);ctx.stroke();ctx.setLineDash([]);emoji('🪔',1535,G-193,40);if(nearPuzzle()){ctx.font='bold 18px sans-serif';ctx.fillStyle='#fff0c9';ctx.fillText('E / USE',1460,G-100)}}ctx.fillStyle='#153d35ee';ctx.beginPath();ctx.roundRect(2780,G-180,200,165,12);ctx.fill();ctx.strokeStyle='#ffcf6d';ctx.lineWidth=2;ctx.stroke();emoji(level===2?'🪔':'🌺',2880,G-140,40);ctx.font='bold 19px sans-serif';ctx.fillStyle='#ffe1a3';ctx.fillText(level===2?'THE PANDAL':'LEVEL EXIT',2880,G-94);ctx.font='16px sans-serif';ctx.fillText('8 modaks · 3 flowers',2880,G-57);if(shield>0||magnet>0){ctx.strokeStyle=shield>0?'#ffdf8a':'#8fe2e8';ctx.lineWidth=3;ctx.beginPath();ctx.arc(player.x+20,player.y+22,40,0,Math.PI*2);ctx.stroke()}mouse(player.x+20,player.y+20);for(const p of particles){if(!['pause','puzzle'].includes(mode)){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=250*dt;p.life-=dt}ctx.globalAlpha=Math.max(0,p.life);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,5,7)}ctx.globalAlpha=1;particles=particles.filter(p=>p.life>0);ctx.restore()}
function frame(t){const dt=Math.min((t-last)/1000||0,.033);last=t;clock+=dt;update(dt);draw(dt);const victory=$('#victory-mouse')||$('#outfit-preview');if(victory){const c=victory.getContext('2d');c.clearRect(0,0,180,80);mouse(100,40,c)}if(clock>hintUntil)$('#toast').style.opacity=0;requestAnimationFrame(frame)}
$('#pause').onclick=pause;$('#interact').onclick=interact;
window.addEventListener('keydown',e=>{if(e.target.closest('button')&&mode!=='play'&&e.code!=='Escape')return;if(['ArrowLeft','ArrowRight','ArrowUp','Space','KeyA','KeyD','KeyW','KeyP','Escape','KeyE'].includes(e.code)){e.preventDefault();if(!e.repeat){if(['Space','ArrowUp','KeyW'].includes(e.code))jump();if(['KeyP','Escape'].includes(e.code))pause();if(e.code==='KeyE')interact()}keys[e.code]=true}});window.addEventListener('keyup',e=>keys[e.code]=false);window.addEventListener('blur',()=>{keys={};if(mode==='play')pause()});document.addEventListener('visibilitychange',()=>{if(document.hidden){keys={};if(mode==='play')pause()}});document.querySelectorAll('[data-key]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys[b.dataset.key]=true;if(b.dataset.key==='Space')jump()});for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>keys[b.dataset.key]=false)});
$('#overlay').addEventListener('keydown',e=>{if(e.key!=='Tab')return;const buttons=[...$('#overlay').querySelectorAll('button:not(:disabled)')];if(!buttons.length)return;const first=buttons[0],last=buttons[buttons.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}});
loadLevel(0);intro();requestAnimationFrame(frame);
